int eventspercycle = 20;  // # events per sphere per cycle
int N = 4000;                         // number of spheres 
int maxcycles = -1;		// maximum number of cycles  // !!!!!!!!!!!!  added  by A. Vorontsov
double initialpf = 0.01;                   // initial packing fraction
double maxpf = ${pf};                   // max packing fraction
double minpf = 0.;                   // min packing fraction  // !!!!!!!!!!!!  added  by A. Vorontsov
double temp = 0.2;    // initial temp., use 0 for zero velocities
double growthrate = ${st};          // growth rate
double maxpressure = 10000.;           // max pressure 
char* readfile = final.xyz	//new            // if new, creates new packing
char* writefile = final.xyz  // after mp2
char* datafile = stats_prep.dat  // data file up to mp2